version: '3.8'

services:
  control-hq-app:
    build: .
    container_name: control-hq
    ports:
      - "8080:8080"
    environment:
      KASA_SMART_PLUG_IPS: ${KASA_SMART_PLUG_IPS}
      TAPO_CAMERAS_IPS: ${TAPO_CAMERAS_IPS}
      TAPO_DEVICE_NAS_ACCOUNT_NAME: ${TAPO_DEVICE_NAS_ACCOUNT_NAME}
      TAPO_DEVICE_NAS_ACCOUNT_PWD: ${TAPO_DEVICE_NAS_ACCOUNT_PWD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    restart: unless-stopped